name: build
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      ### restore caches
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install build dependencies
        run: |
          npm ci
      - name: run tests
        run: |
          npm test