on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: |
        npm ci
    - name: test
      run: |
        npm test
      env:
        CI: true
  publish:
    name: Publish package release
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use npmjs.org registry
      uses: actions/setup-node@v1
      with:
        registry-url: https://registry.npmjs.org/
    - name: publish to npmjs.com
      run: |
        npm publish --access public
      env:
         NPM_TOKEN: ${{secrets.NPM_TOKEN}}
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
